apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${ACCOUNT_ID}:role/${INGRESS_EXTERNAL_DNS_ROLE_NAME}
  name: ingress-external-dns-serviceaccount
  namespace: career-roadmap-app