apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${ACCOUNT_ID}:role/${INGRESS_CONTROLLER_ROLE_NAME}
  name: ingress-controller-serviceaccount
  namespace: career-roadmap-app