apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../manifests/base
namespace: prod-career-roadmap-app
namePrefix: prod-

patches:
- path: api/deployment.yml
- path: ingress/ingress.yml
